# Starter pipeline
# Pipeline for Tines Tunnel Docker container
# new line


trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: DockerCompose@0
      displayName: 'Build Docker images'
      inputs:
        dockerComposeFile: 'docker-compose.yml'
        action: 'Build'
    - task: Docker@2
      displayName: 'Push Docker image to ACR'
      inputs:
        command: 'push'
        repository: 'rabellanacr.azurecr.io/tines-tunnel'
        containerRegistry: 'ACRConnection'
        tags: |
          $(Build.BuildId)

- stage: Deploy
  jobs:
  - job: Deploy
    steps:
    - task: DockerCompose@0
      displayName: 'Deploy Docker containers'
      inputs:
        dockerComposeFile: 'docker-compose.yml'
        action: 'Up'
